MovieShopMVC/Controllers/CastController.cs
using System.Threading.Tasks;
using ApplicationCore.RepositoryInterface;
using ApplicationCore.ServiceInterface;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class CastController : Controller
    {
        // GET
        private ICastService _castService;

        public CastController(ICastService castService)
        {
            _castService = castService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var cast =await _castService.GetCastDetails(id);
            return View(cast);
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterface;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling Web API for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MovieShopMVC.Controllers
{
    
    public class MoviesController : Controller
    {
        private IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }
        public async Task<IActionResult> Details(int id)
        {
            var movie =await _movieService.GetMoiveDetails(id);
            return View(movie);
        }
        

    }
}

MovieShopMVC/Controllers/UserController.cs
using System;
using System.Threading.Tasks;
using ApplicationCore.Models;
using ApplicationCore.ServiceInterface;
using Microsoft.AspNetCore.Mvc;

namespace MovieShopMVC.Controllers
{
    public class UserController : Controller
    {
        private ICurrentUser _currentUser;
        private IUserService _userService;
        private IPurchaseService _purchaseService;
        public UserController(ICurrentUser currentUser,IUserService userService,IPurchaseService purchaseService)
        {
            _currentUser = currentUser;
            _userService = userService;
            _purchaseService = purchaseService;
        }

        public async Task<IActionResult> PurchasedMovies()
        {
            var userid = _currentUser.UserId;
            var moviecard =await _userService.GetPurchasedMovies(userid);
            return View(moviecard);
        }

        public async Task<IActionResult> ViewUserProfile()
        {
            var email = _currentUser.Email;
            var user =await _userService.GetUserDetails(email);
            return View(user);
        }
        [HttpGet]
        public IActionResult ConfirmPurchase(int mid)
        {
            var purchaseMovie = new UserPurchaseMovieRequestModel();
            purchaseMovie.MovieId = mid;
            purchaseMovie.UserId = _currentUser.UserId;
            // purchaseMovie.TotalPrice = price;
            return View(purchaseMovie);
        }
        [HttpPost]
        public async Task<IActionResult> ConfirmPurchase(UserPurchaseMovieRequestModel model)
        {
            var createPurchase = await _purchaseService.PurchaseMovie(model);
            return Redirect("~/");
        }
        
    }
}

MovieShopMVC/Views/Movies/Details.cshtml
@model ApplicationCore.Models.MovieDetailResponseModel

@{
    ViewData["Title"] = "Movie Detail Page";
}
@*Top Movie Info*@

<div class="row text-white" style="background:linear-gradient(rgba(192, 192, 192, 0.45), rgba(192, 192, 192, 0.45)), url(@Model.PosterUrl);background-repeat: no-repeat; background-size: cover;">
    <div class="col align-content-center">
            <img src="@Model.PosterUrl" class="img-fluid" alt="@Model.Title">
        </div>
    <div class="col-6 align-content-center">
        <h2>@Model.Title</h2>
        <p class="">@Model.Tagline</p>
        <div class="row">
            <div class="col">
                <span>@Model.RunTime m</span> | <span>@Model.ReleaseDate.Value.Year</span>
            </div>
            <div class="col">
                @foreach (var genre in @Model.Genres)
                {
                    <span class="badge bg-secondary">@genre.Name</span>
                }
            </div>
        </div>
        <span class="badge bg-warning text-dark">@Model.Rating</span>
        <p>@Model.Overview</p>
    </div>
    <div class="col">
        <div class="btn-group-vertical">
            <a type="button" class="btn btn-outline-light mt-3"><i class="fas fa-edit"></i>REVIEW</a>
            <a type="button" class="btn btn-outline-light mt-3"><i class="fas fa-play"></i>TRAILER</a>
            @if (User.Identity.IsAuthenticated)
            {
                <a type="button" class="btn btn-outline-light mt-3"
                   asp-action="ConfirmPurchase" asp-controller="User" asp-route-mid="@Model.Id">
                    <span>BUY @Model.Price</span>
                </a>
            }
            else
            {
                <a type="button" class="btn btn-outline-light mt-3 disabled"
                   asp-action="ConfirmPurchase" asp-controller="User" asp-route-mid="@Model.Id">BUY @Model.Price</a>
            }
            <a type="button" class="btn btn-outline-light mt-3 disabled">WATCH MOVIE</a>
        </div>
    </div>
</div>

@*Left Movie Facts*@
@*Right Cast Info*@
<div class="row mt-3">
    <div class="col-4 bg-light">
        <h4>MOVIE FACTS</h4>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><i class="far fa-calendar-alt"></i>&nbsp;Release Date&nbsp;<span class="badge bg-secondary text-white">@Model.ReleaseDate.Value.Year</span></li>
          <li class="list-group-item"><i class="fas fa-hourglass-half"></i>&nbsp;Run Time&nbsp;<span class="badge bg-secondary text-white">@Model.RunTime m</span></li>
          <li class="list-group-item"><i class="far fa-money-bill-alt"></i>&nbsp;Box Office&nbsp;<span class="badge bg-secondary text-white">$$@Model.Revenue</span></li>
          <li class="list-group-item"><i class="fas fa-dollar-sign"></i>&nbsp;Budget&nbsp;<span class="badge bg-secondary text-white">$$@Model.Budget</span></li>
          <li class="list-group-item"><i class="fab fa-imdb fa-2x"></i>&nbsp;&nbsp;&nbsp;&nbsp;<i class="fas fa-share-square fa-2x"></i></li>
        </ul>
    </div>
    <div class="col-8">
        <h4>CAST</h4>
        <ul class="list-group list-group-flush">
            @foreach (var cast in @Model.Casts)
            {
                <a asp-controller="Cast" asp-action="Details" asp-route-id="@cast.Id">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col"><img class="img-fluid castlistimg" src="@cast.ProfilePath" style=""></div>
                            <div class="col">@cast.Name</div>
                            <div class="col">@cast.Character</div>
                        </div>
                    </li>    
                </a>
            }
        </ul>
    </div>
</div>